# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-23 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(null=True, to='app01.Author'),
        ),
    ]
