# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-09-22 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='username',
        ),
    ]
